### PR TITLE
 Uninstall function, microG installation and some hacks

### PR DESCRIPTION
**Pull request by ayasa520**

### CODE REVIEW

**Comment by ayasa520** [comment]
close https://github.com/casualsnek/waydroid_script/issues/18 https://github.com/casualsnek/waydroid_script/issues/49

**Comment by casualsnek** [comment]
Hey there ! May i know what is the state this PR ? I see a lot of improvement and additions in your branch !

**Comment by ayasa520** [comment]
I basically have nothing more to add. There are some conflicts, which I will resolve when I have time.

**Comment by ayasa520** [comment]
I think everything is ready now.

**Pull request merged**
