### PR TITLE
Various grammar fixes

### PR DESCRIPTION
**Pull request by mak448a**

### CODE REVIEW

**Comment by burgerzuhsaga** [comment]
Hey! There are another fork of waydroid_script: https://github.com/burgerzuhsaga/waydroid_script 
You can open merge request there

**Comment by casualsnek** [comment]
> Hey! There are another fork of waydroid_script: https://github.com/burgerzuhsaga/waydroid_script You can open merge request there
I've removed your comments from other PR threads as you were spamming it all over. If you have additional features and reasons to switch from this repo to yours please create a new issue thread informing users about your work instead !

**Comment by casualsnek** [comment]
> _ No description provided. _

There seems be some conflicts for merging, can you clean those up so i can merge the grammar and spelling fixes !

**Comment by mak448a** [comment]
I've fixed the conflicts

**Pull request merged**
