### PR TITLE
Update to Magisk Delta 26.3

### PR DESCRIPTION
**Pull request by mistrmochov**
Your script works fine with last Magisk Delta (before Kitsune Mask update).

Also with modified setup for bootanim

### CODE REVIEW

**Comment by casualsnek** [comment]
Thanks, I'll merge this once I test and confirm if it works properly, including features like zygisk and module installation !

**Comment by mistrmochov** [comment]
Hi, Well unfortunately I only have this all file for the magisk app, don't have clone of the old repo, but I think there will probably be some forks on Github.

**Comment by mistrmochov** [comment]
Hi again, I think I found some fork, here: https://github.com/shuixi2013/Magisk-Delta

**Comment by baptx** [comment]
I found a copy of the APK file on https://web.archive.org/web/20240109183234/https://github.com/HuskyDG/magisk-files-old/releases.
With the Linux diff command, we can see it matches the one from the pull request so we can also use https://web.archive.org/web/20240109183234mp_/https://github.com/HuskyDG/magisk-files-old/releases/download/0fe46c5a-delta/app-release.apk for the dl_link variable.
I also needed the modified bootanim_component variable from the pull request and was able to install Magisk. However it still says "Zygisk: No". Is there a solution for that?

**Comment by casualsnek** [comment]
> I found a copy of the APK file on https://web.archive.org/web/20240109183234/https://github.com/HuskyDG/magisk-files-old/releases (if you see a login form, you just need to scroll down). With the Linux diff command, we can see it matches the one from the pull request so we can also use https://web.archive.org/web/20240109183234mp_/https://github.com/HuskyDG/magisk-files-old/releases/download/0fe46c5a-delta/app-release.apk for the dl_link variable. I also needed the modified bootanim_component variable from the pull request and was able to install Magisk. However it still says "Zygisk: No" even when enabling Zygisk in Magisk settings and rebooting. Is there a solution for that?

Zygisk sometimes only works when magisk is installed via magisk ! If you have su access, use the magisk app and install using 'Install directly to system partition' and reboot. If that works and zygisk starts up, i will merge this. Thanks for trying it !

**Comment by mistrmochov** [comment]
That's what this pull request would fix. Zygisk would work totally fine, with this different bootanim script

**Comment by baptx** [comment]
I have su access and Zygisk works when selecting "Direct Install into system partition" and rebooting, thanks for your contributions!
Now when booting Waydroid, there is just a popup error "Android System" / "There's an internal problem with your device. Contact your manufacturer for details." so I have to close it, is it normal? There was also another option "Direct Install (Recommended)", isn't it better and working for Zygisk?
By the way, is there any reason for using a fork instead of the official Magisk?
I also tried to pass SafetyNet / Play Integrity (tested with Play Integrity API Checker from Google Play Store) using Magisk modules like https://github.com/kdrag0n/safetynet-fix and https://github.com/Displax/safetynet-fix but it is not working (even when modifying waydroid_base.prop: https://github.com/waydroid/waydroid/issues/935#issuecomment-1880040679 and enabling the setting "Hide the Magisk app"), maybe you have an idea, there is an issue for that:
https://github.com/waydroid/waydroid/issues/182

**Comment by mistrmochov** [comment]
Hi again, the message with internal problem is pretty common in Waydroid, when installing bunch of modules, but as far as I know, It will not cause any issues.
Bypassing SafetyNet Is unfortunately not possible at all on emulated androids

**Comment by baptx** [comment]
Hi, let me know if you have an idea for my other questions.
I also noticed after installing Magisk, the phone is detected as rooted on many steps with the app https://github.com/KimChangYoun/rootbeerFresh and the Magisk fork from this pull request does not include the Zygisk "Enforce DenyList" option which is a replacement to MagiskHide to hide root:
https://droidwin.com/how-to-hide-root-from-apps-via-magisk-denylist/

> Various developers picked up that task and with the introduction of Zygis in Magisk, you once again have the option to hide root from apps and games using its DenyList feature.

> Enable Zygisk and Enforce DenyList
> Launch the Magisk App on your device and tap on the Settings icon situated at the top right.
> After that, scroll to the Magisk section and enable the toggle next to Zygisk and Enforce Deny List.

Is there a way to get either MagiskHide or the "Enforce DenyList" option, maybe with another Magisk version?

**Comment by baptx** [comment]
@casualsnek It would be better for security to host app-release.apk on your own repository instead of a third-party repository (since the repository could be removed or inject malware in the APK file if you don't use the link to the specific version https://github.com/mistrmochov/magiskdeltaorig/raw/793a78430bac879b8eb9bf72d03003ebc205c294/app-release.apk).

**Comment by casualsnek** [comment]
> @casualsnek It would be better for security to host app-release.apk on your own repository instead of a third-party repository (since the repository could be removed or inject malware in the APK file if you don't use the link to the specific version https://github.com/mistrmochov/magiskdeltaorig/raw/793a78430bac879b8eb9bf72d03003ebc205c294/app-release.apk).

Thanks, I have saved a copy and will switch to using it if required !

> By the way, is there any reason for using a fork instead of the official Magisk?
Yes, waydroid is different than typical android devices like, missing fstab, selinux support and so on. We at one point able to get su working but eventually found magisk-delta could be setup in waydroid more easily as it targeted emulators and devces that are alightly different as well , so we started using it.

**Comment by sivakuttan156** [comment]
@baptx how you managed to get the direct install to system partition I'm not getting it after installing the kitsune version from your link

**Comment by baptx** [comment]
@sivakuttan156 It was a long time ago so I don't remember the details but the README from https://github.com/casualsnek/waydroid_script also mentions "Direct Install into system partition".
You can create a new issue so others can help if needed.

**Pull request merged**
